#!/bin/bash

echo "=========================================="
echo "  PUSH TO GITHUB"
echo "=========================================="
echo ""
echo "Repository: https://github.com/Ianmabruk/POSify.git"
echo ""
echo "You'll need to enter your GitHub credentials:"
echo "  Username: Ianmabruk"
echo "  Password: Your GitHub Personal Access Token"
echo ""
echo "Don't have a token? Create one at:"
echo "  https://github.com/settings/tokens"
echo "  (Select 'repo' scope)"
echo ""
echo "Pushing to GitHub..."
echo ""

git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "=========================================="
    echo "  ✅ SUCCESS!"
    echo "=========================================="
    echo ""
    echo "Your code is now on GitHub:"
    echo "  https://github.com/Ianmabruk/POSify"
    echo ""
    echo "Next steps:"
    echo "  1. Go to https://app.netlify.com"
    echo "  2. Click 'Add new site' → 'Import from Git'"
    echo "  3. Select your GitHub repo"
    echo "  4. Deploy!"
    echo ""
else
    echo ""
    echo "=========================================="
    echo "  ❌ PUSH FAILED"
    echo "=========================================="
    echo ""
    echo "Common issues:"
    echo "  1. Wrong credentials"
    echo "  2. Need Personal Access Token (not password)"
    echo "  3. Token needs 'repo' permissions"
    echo ""
    echo "Create token at: https://github.com/settings/tokens"
    echo ""
fi
